version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=postgres user=postgres password=yourpassword dbname=resumebuilder port=5432 sslmode=disable
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ResumeBuilder_user
      POSTGRES_PASSWORD: kali
      POSTGRES_DB: ResumeBuilder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
